dailyfresh/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

]

dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),

]

dailyfresh/user/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # re_path(r'^register/$', views.register, name='register'),
    # path('register_handle/', views.register_handle,name='register_handle'),  # 注册处理
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'^active/(?P<token>[\s\S]*)/', views.ActiveView.as_view(), name='active'),  # 用户激活
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),  # 登录
    re_path(r'^text/(?P<token>[\s\S]*)/', views.text1.as_view()),  # 用户激活
    # re_path(r'^info/$', login_required(views.UserInfoView.as_view()),name='info'),
    # re_path(r'^order/$', login_required(views.UserOrderView.as_view()), name='order'),
    # re_path(r'^site/$', login_required(views.UserSiteView.as_view()), name='site'),
    re_path(r'^info/$', views.UserInfoView.as_view(), name='info'),
    re_path(r'^order/$', views.UserOrderView.as_view(), name='order'),
    re_path(r'^site/$', views.UserSiteView.as_view(), name='site'),
    re_path(r'^logout/$',views.LogoutView.as_view(),name='logout'),
]

dailyfresh/templates/base_bottom.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    {#网页标题#}
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
  <link rel="stylesheet" type="text/css" href="/static/css/main.css">
  <script type="text/javascript" src = '/static/js/jquery-1.12.4.min.js'></script>
  {% block topfile %}{% endblock topfile %}

  {% block head%}
  {% endblock head%}

</head>
<body>
{#网页顶部#}
{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/templates/df_goods/index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

{% block body %}

{% endblock body %}
    <div class= "footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="https://www.cnblogs.com/shuimohei/p/13113618.html">感谢</a>
            <span>|</span>
            <a href="https://www.cnblogs.com/shuimohei/p/13113618.html">友情链接</a>
            <span>|</span>
        </div>
    </div>
    {#网页底部html文件块#}
    {% block bottom %}{% endblock bottom %}
    {#网页底部引入文件块#}
    {% block bottomfile %}{% endblock bottomfile %}
</body>
</html>

dailyfresh/templates/base_detail_list.html
{% extends 'base_bottom.html' %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {%  block main_content %}{% endblock main_content %}
{% endblock body %}

dailyfresh/templates/base_no_cart.html
{% extends 'base_bottom.html' %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/templates/df_goods/index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

dailyfresh/templates/base_user_center.html
{% extends 'base_no_cart.html' %}

{% block title%}用户中心{% endblock title %}
{% block page_title%}用户中心{% endblock page_title %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}"{% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}"{% if page == 'order' %} class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}"{% if page == 'site' %} class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {#    用户中心右侧内容块#}
    {% block right_content %}{% endblock right_content %}
    </div>

{% endblock body %}